export const oneBeeSchoolList = [
    "able", "again", "angry", "anybody", "April", 
    "back", "barely", "bedroom", "bike", "blank", 
    "block", "bow", "brain", "branch", "brave", 
    "bride", "bright", "broken", "chin", "climb", 
    "cloth", "coat", "cool", "corner", "create", 
    "credit", "crown", "dance", "dazzle", "deal", 
    "dear", "doctor", "dots", "edge", "endless", 
    "enter", "evening", "find", "first", "float", 
    "four", "front", "give", "glue", "grand", 
    "grid", "gross", "ground", "hair", "hard", 
    "heap", "his", "hug", "join", "ladder", 
    "later", "letter", "little", "live", "May", 
    "mile", "more", "mother", "mound", "music", 
    "name", "near", "nest", "notebook", "open", 
    "other", "overcome", "park", "pat", "peel", 
    "plunger", "point", "pole", "pour", "present", 
    "pride", "really", "river", "roast", "rude", 
    "rug", "scan", "scream", "second", "shall", 
    "shower", "sketch", "sky", "snack", "snail", 
    "snake", "snap", "solve", "spark", "spoon", 
    "spring", "stall", "state", "steel", "stew", 
    "stood", "store", "stove", "subway", "tape", 
    "this", "Thursday", "tide", "together", "toss",
    "tubes", "tug", "tune", "vase", "wag", 
    "wake", "wedding", "while", "whisper", "why", "wish", 
    "worth", "zip"
  ];
