export const threeBeeSchoolList = [
    "acclimate", "aerosol", "Albuquerque", "altimeter", "animatronics", 
    "antechamber", "antimony", "aptitude", "arable", "aspirin", 
    "Assam", "attorney", "aura", "avens", "bilge", 
    "Bunsen burner", "centrifuge", "chasm", "Chicana", "coccidiosis", 
    "coleus", "conciliatory", "conjunto", "contagion", "contemptible", 
    "Copenhagen", "deadpan", "defoliant", "demure", "dendrochronology", 
    "destitution", "dilute", "divot", "dynasty", "ellipsis", 
    "elongated", "Erlenmeyer flask", "expulsion", "extravagant", 
    "Gilgamesh", "gorilla", "grebe", "haw", "hitherto", 
    "horticulture", "hypocaust", "Illinois", "incandescent", "incense", 
    "indignant", "innards", "insolent", "insufferable", "interstellar", 
    "jeopardy", "jugular", "koi", "kung fu", "lasso", 
    "Laundromat", "luciferin", "lymphoma", "Macao", "Macedonia", 
    "malicious", "malignant", "malnutrition", "matterhorn", "meitnerium",
    "metronome", "Mumbai", "nitrogen", "nondescript", "Okefenokee", 
    "palomino", "paralysis", "patronize", "peplos", "petticoat",
    "photosynthesis", "pinyin", "pipette", "Pleiades", "Popocatepetl", 
    "propitious", "quarry", "Ramadan", "recede", "refuge", 
    "repose", "retinitis pigmentosa", "sauna", "scandium", "senescent", 
    "Shaanxi", "shoal", "silicon", "snivel", "societal",
    "sphagnum", "sprocket", "Sumerian", "surfactant", "Taoism",
    "Tetrazzini", "thyroid", "tripe", "tunic", "turquoise", 
    "uncanny", "Versailles", "wok"
  ];