export const twoBeeSchoolList = [
    "ailment", "ambush", "amphitheater", "appreciation", "Arabic", 
    "Arctic", "awfully", "bronze", "Brooklyn", "buckeye", 
    "captain", "cereal", "combat", "completely", "composition", 
    "confident", "congregation", "cress", "dapper", "delegation", 
    "dessert", "devotion", "diamond", "disdain", "disgruntled", 
    "doughnut", "drawl", "droll", "engulf", "expressway", 
    "fallow", "flea", "forearms", "fowl", "fragrant", 
    "furniture", "fury", "gallon", "gather", "graduate", 
    "gratitude","ignore", "important", "improve", "incubator",
    "information", "inscription", "insulation", "insult", "Internet", 
    "intertwine", "intimidate", "inventory", "invisible", "mantel", 
    "manual", "marble", "mischievous", "nighttime", "occupy", 
    "oddity", "Oman", "ourselves", "pantry", "peaceful", 
    "platypus", "plaza", "poisonous", "possible", "pouch", 
    "practice", "precious", "privilege", "provision", "putty", 
    "quotation", "razor", "recital", "reference", "reindeer", 
    "replace", "replica", "responsible", "rotten", "sacred", 
    "salute", "saucer", "sausage", "sentinel", "serenity", 
    "sewing", "silence", "spacious", "squash", "squire", 
    "stagecoach", "stroll", "superior", "termite", "terrify", 
    "thorax", "thousand", "transform", "turban", "valley", 
    "vision", "voracious","wisdom", "yesterday"
  ];